collections:
    topics:
        output: true
        permalink: /topics/:path/
defaults:
    -   scope:
            path: ""
            type: topics
        values:
            layout: topic


repository: staceb/experimentingwithjekyll
